.TH LIMINE 1 "version g008fcfb7" "August 2026"
.SH NAME
limine \- Multiplexer to several Limine-related utilities.
.SH SYNOPSIS
.B limine
.RI "<command> <args...>"
.SH DESCRIPTION
\fBlimine\fR provides a series of Limine-related utilities condensed in a single executable.
.SH BUGS
Please report bugs via
.IR https://github.com/Limine-Bootloader/Limine/issues .
.SH HOMEPAGE
.I https://limine-bootloader.org/
