name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
       submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nasm llvm lld
    - name: Do limine things
      run: |
        cd limine
          ./bootstrap
          ./configure --enable-bios --enable-uefi-x86-64
          make
    - name: Run check
      run: |
        make -f Makefile
