name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
       submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nasm llvm lld

    - name: Do limine things
      run: |
          ./limine/bootstrap
          ./limine/configure

    - name: Run check
      run: |
        pwd
        echo "===== Makefile ====="
        head -20 Makefile
        echo "===== make database ====="
        make -pn | grep -E '^all1:|^all:|^kernel:|^image:'
        echo "===== dry run ====="
        make -n
